/*
*	New Java File starts here.
*	This file should be named c_struct2.java
*	Automatically generated by NML CodeGen Java Applet.
*	from nml_test_format.hh:117
*	with command line arguments :  generate_for_all_langs=true HHFile=nml_test_format.hh
*
*	.gen script :
*		0:load nml_test_format.hh
*		1:clear
*		2:select_from_file nml_test_format.hh
*		3:generate C protos>nml_test_format_c_n.h
*		4:generate C format>nml_test_format_c_n.c
*		5:generate C update>nml_test_format_c_n.c
*		6:generate C++ protos>nml_test_format_n_codegen_protos.hh
*		7:generate C++ format>nml_test_format_n.cc
*		8:generate C++ update>nml_test_format_n.cc
*		9:generate C++ constructor>nml_test_format_n.cc
*		10:generate Java dict>nml_test_format_MsgDict.java
*		11:generate Java classes >*
*		12:generate Ada spec>nml_test_format_n_ada.ads
*		13:generate Ada body>nml_test_format_n_ada.adb
*		14:exit
*
*/

// Import all NML and posemath interfaces
import rcs.nml.*;
import rcs.posemath.*;

/*
*	Class definition for c_struct2
*	Automatically generated by NML CodeGen Java Applet.
*/
public class c_struct2 implements Cloneable
{
	public byte csc2 = 0;
	public int csi2 = 0;


	// Constructor 
	public c_struct2()
	{

	}


	public void update(NMLFormatConverter nml_fc)
	{

		nml_fc.beginClass("c_struct2",null);
		csc2 = nml_fc.update_with_name("csc2",csc2);
		csi2 = nml_fc.update_with_name("csi2",csi2);

		nml_fc.endClass("c_struct2",null);

	}


	public c_struct2 clone() throws CloneNotSupportedException
	{
		c_struct2 cloned_object = (c_struct2) super.clone();
		return cloned_object;

	}


	/* Getters and Setters */
	public byte getcsc2() {
		return (csc2);
	}
	public void setcsc2(byte _csc2)  {
		this.csc2=_csc2;
	}

	public int getcsi2() {
		return (csi2);
	}
	public void setcsi2(int _csi2)  {
		this.csi2=_csi2;
	}


}

