/*
*	New C++ Header  File starts here.
*	This file should be named cgtester_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=cgtester.hh dla_length_init=2
*	RCS_VERSION=@(#) RCS_LIBRARY_VERSION: 2009.06.04_1506 Compiled on Fri Jun  5 08:49:50 EDT 2009 for the java platform.
*	$Id: cgtester_n_codegen_protos.hh 1510 2009-06-08 13:27:21Z shackle $
*
*	.gen script :
*		0:load cgtester.hh
*		1:clear
*		2:select_from_file cgtester.hh
*		3:generate C++ protos>cgtester_n_codegen_protos.hh
*
*/

#ifndef cgtester_n_codegen_protos_hh_included
#define cgtester_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "cgtester.hh"

// Forward Function Prototypes
extern void nmlupdate(CMS *cms, mystruct *x);
extern void initialize_mystruct(mystruct *x);
extern void nmlupdate(CMS *cms, NML_UNBOUNDED_LENGTH_ARRAY INSIDE_COMMAND *x);
extern void nmlupdate(CMS *cms, NML_UNBOUNDED_LENGTH_ARRAY mystruct *x);


#ifndef MAX_CGTESTER_NAME_LENGTH
#define MAX_CGTESTER_NAME_LENGTH 16
#endif
#ifndef CGTESTER_NAME_LIST_LENGTH
#define CGTESTER_NAME_LIST_LENGTH 4
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE cgtester_id_list[CGTESTER_NAME_LIST_LENGTH];
extern const size_t cgtester_size_list[CGTESTER_NAME_LIST_LENGTH];

// Enumerated Type Constants

extern int cgtester_format(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif cgtester_n_codegen_protos_hh_included */ 

