/*
*	New C++ Header  File starts here.
*	This file should be named echo_types_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  generate_for_all_langs=true HHFile=echo_types.hh
*
*	.gen script :
*		0:load echo_types.hh
*		1:clear
*		2:select_from_file echo_types.hh
*		3:generate C protos>echo_types_c_n.h
*		4:generate C format>echo_types_c_n.c
*		5:generate C update>echo_types_c_n.c
*		6:generate C++ protos>echo_types_n_codegen_protos.hh
*		7:generate C++ format>echo_types_n.cc
*		8:generate C++ update>echo_types_n.cc
*		9:generate C++ constructor>echo_types_n.cc
*		10:generate Java dict>echo_types_MsgDict.java
*		11:generate Java classes >*
*		12:generate Ada spec>echo_types_n_ada.ads
*		13:generate Ada body>echo_types_n_ada.adb
*		14:exit
*
*/

#ifndef echo_types_n_codegen_protos_hh_included
#define echo_types_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "echo_types.hh"

// Forward Function Prototypes


#ifndef MAX_ECHO_NAME_LENGTH
#define MAX_ECHO_NAME_LENGTH 11
#endif
#ifndef ECHO_NAME_LIST_LENGTH
#define ECHO_NAME_LIST_LENGTH 3
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE ECHO_id_list[ECHO_NAME_LIST_LENGTH];
extern const size_t ECHO_size_list[ECHO_NAME_LIST_LENGTH];

// Enumerated Type Constants

extern int ECHO_format(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif echo_types_n_codegen_protos_hh_included */ 

