/*
*	New C++ Header  File starts here.
*	This file should be named nml_test_unbounded_format_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  generate_for_all_langs=true HHFile=nml_test_unbounded_format.hh
*	RCS_VERSION=@(#) RCS_LIBRARY_VERSION: 2009.01.21_1322:1328 Compiled on Thu Jan 22 08:08:48 EST 2009 for the java platform.
*	$Id: CodeGenCommon.java 1325 2009-01-21 17:59:02Z shackle $
*
*	.gen script :
*		0:load nml_test_unbounded_format.hh
*		1:clear
*		2:select_from_file nml_test_unbounded_format.hh
*		3:generate C protos>nml_test_unbounded_format_c_n.h
*		4:generate C format>nml_test_unbounded_format_c_n.c
*		5:generate C update>nml_test_unbounded_format_c_n.c
*		6:generate C++ protos>nml_test_unbounded_format_n_codegen_protos.hh
*
*/

#ifndef nml_test_unbounded_format_n_codegen_protos_hh_included
#define nml_test_unbounded_format_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "nml_test_unbounded_format.hh"

// Forward Function Prototypes
extern void nmlupdate(CMS *cms, ntu_s1 *x);
extern void initialize_ntu_s1(ntu_s1 *x);


#ifndef MAX_NML_TEST_UNBOUNDED_NAME_LENGTH
#define MAX_NML_TEST_UNBOUNDED_NAME_LENGTH 23
#endif
#ifndef NML_TEST_UNBOUNDED_NAME_LIST_LENGTH
#define NML_TEST_UNBOUNDED_NAME_LIST_LENGTH 2
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE nml_test_unbounded_id_list[NML_TEST_UNBOUNDED_NAME_LIST_LENGTH];
extern const size_t nml_test_unbounded_size_list[NML_TEST_UNBOUNDED_NAME_LIST_LENGTH];
extern const char nml_test_unbounded_name_list[NML_TEST_UNBOUNDED_NAME_LIST_LENGTH][MAX_NML_TEST_UNBOUNDED_NAME_LENGTH];
extern const char *nml_test_unbounded_symbol_lookup(long type);


// Enumerated Type Constants

extern int nml_test_unbounded_format(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif nml_test_unbounded_format_n_codegen_protos_hh_included */ 

