--
--	New Ada Body File starts here.
--	This file should be named otherheader_n_ada.adb
--	Automatically generated by NML CodeGen Java Applet.


with Nml_Msg; use Nml_Msg;

with Posemath_N_Ada;  use Posemath_N_Ada;

with Cms;


--	Some standard Ada Packages we always need.
with Unchecked_Deallocation;
with Unchecked_Conversion;
with Interfaces.C; use Interfaces.C;
with Interfaces.C.Strings; use Interfaces.C.Strings;

package body otherheader_n_ada is

	-- Create some common variables  and functions needed for updating Enumeration types.

	-- Every NMLmsg type needs an update and an initialize function.

	procedure Update_struct_from_other_header(Cms_Ptr : in Cms.Cms_Access; Msg : in struct_from_other_header_Access) is
	begin
		Cms.Begin_Class(Cms_Ptr,"struct_from_other_header","");
		Cms.Update_Char(Cms_Ptr, "x", Msg.x);
		Cms.End_Class(Cms_Ptr,"struct_from_other_header","");
	end Update_struct_from_other_header;

	procedure Update_Internal_struct_from_other_header(Cms_Ptr : in Cms.Cms_Access; Msg : in out struct_from_other_header) is
	begin
		Cms.Begin_Class(Cms_Ptr,"struct_from_other_header","");
		Cms.Update_Char(Cms_Ptr, "x", Msg.x);
		Cms.End_Class(Cms_Ptr,"struct_from_other_header","");
	end Update_Internal_struct_from_other_header;




	function Format(Nml_Type : in long;
			Msg : in NmlMsg_Access;
			Cms_Ptr : in Cms.Cms_Access)
				return int is
	begin
		return 1;
	end Format;

end otherheader_n_ada;

-- End of Ada Body file  otherheader_n_ada.adb

