--
--	New Ada Spec File starts here.
--	This file should be named otherheader_n_ada.ads
--	Automatically generated by NML CodeGen Java Applet.
with Nml_Msg; use Nml_Msg;
with Cms;

with Posemath_N_Ada;  use Posemath_N_Ada;


--	Some standard Ada Packages we always need.
with Unchecked_Deallocation;
with Unchecked_Conversion;
with Interfaces.C; use Interfaces.C;

package otherheader_n_ada is

	-- Create Ada versions of the Enumeration types.

	function Format(Nml_Type : in long;
			Msg : in NmlMsg_Access;
			Cms_Ptr : in Cms.Cms_Access)
				return int;

	pragma Export(C,Format,"ada_otherheader_n_ada_format");


	-- Redefine the C++ NML message classes as Ada Records.

	type struct_from_other_header is 
		record
			x : char;
		end record;

	type struct_from_other_header_Access is access all struct_from_other_header;
	procedure Update_Internal_struct_from_other_header(Cms_Ptr : in Cms.Cms_Access; Msg : in out struct_from_other_header);
	procedure Free is new Unchecked_Deallocation(struct_from_other_header,struct_from_other_header_Access);
	type struct_from_other_header_Array is array(Integer range <>) of struct_from_other_header;


end otherheader_n_ada;

-- End of Ada spec file  otherheader_n_ada.ads

