--
--      New Ada Spec File starts here.
--      This file should be named test_msg.ads
--      Automatically generated by NML CodeGen Java Applet.
--      on Thu Aug 19 15:55:15 EDT 2004
--

with Nml;


--      Some standard Ada Packages we always need.
with Unchecked_Deallocation;
with Unchecked_Conversion;
with Interfaces.C; use Interfaces.C;

package test_msg is

        function Format(Nml_Type : in long;
                        Msg : in Nml.NmlMsg_Access;
                        Cms : in Nml.Cms_Access)
                                return int;

        pragma Export(C,Format,"ada_test_msg_format");


        -- Redefine the C++ NML message classes as Ada Records.

        TEST_B_MSG_TYPE : constant := 1002;

        type TEST_B_MSG is new Nml.NmlMsg with
                record
                        i : int;
                end record;

        type TEST_B_MSG_Access is access all TEST_B_MSG;
        procedure Initialize(Msg : in out TEST_B_MSG);
        function NmlMsg_to_TEST_B_MSG is new Unchecked_Conversion(Nml.NmlMsg_Access,TEST_B_MSG_Access);
        procedure Free is new Unchecked_Deallocation(TEST_B_MSG,TEST_B_MSG_Access);

        TEST_MSG_TYPE : constant := 1001;

        type TEST_MSG is new Nml.NmlMsg with
                record
                        i : int;
                        ia : Nml.Int_Array(1..10);
                        ida_length : int;
                        ida : Nml.Int_Array(1..8);
                end record;

        pragma Pack(TEST_MSG);

        type TEST_MSG_Access is access all TEST_MSG;
        procedure Initialize(Msg : in out TEST_MSG);
        function NmlMsg_to_TEST_MSG is new Unchecked_Conversion(Nml.NmlMsg_Access,TEST_MSG_Access);
        procedure Free is new Unchecked_Deallocation(TEST_MSG,TEST_MSG_Access);


end test_msg;

-- End of Ada spec file  test_msg.ads

