/*
*	New C++ Header  File starts here.
*	This file should be named bgn_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=bgn.hh
*
*	.gen script :
*		0:load bgn.hh
*		1:clear
*		2:select_from_file bgn.hh
*		3:generate C++ protos>bgn_n_codegen_protos.hh
*		4:generate C++ format>bgn_n.cc
*		5:generate C++ update>bgn_n.cc
*		6:generate C++ constructor>bgn_n.cc
*		7:exit
*
*/

#ifndef bgn_n_codegen_protos_hh_included
#define bgn_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "bgn.hh"
#include "my_app_common_statusn.hh"

// Forward Function Prototypes


#ifndef MAX_BGNAME_LENGTH
#define MAX_BGNAME_LENGTH 13
#endif
#ifndef BGNAME_LIST_LENGTH
#define BGNAME_LIST_LENGTH 6
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE bgid_list[BGNAME_LIST_LENGTH];
extern const size_t bgsize_list[BGNAME_LIST_LENGTH];

// Enumerated Type Constants

extern int bgFormat(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif bgn_n_codegen_protos_hh_included */ 

