/*
*	New C++ Header  File starts here.
*	This file should be named pose_datan_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=pose_datan.hh
*
*	.gen script :
*		0:load pose_datan.hh
*		1:clear
*		2:select_from_file pose_datan.hh
*		3:generate C++ protos>pose_datan_n_codegen_protos.hh
*		4:generate C++ format>pose_datan_n.cc
*		5:generate C++ update>pose_datan_n.cc
*		6:generate C++ constructor>pose_datan_n.cc
*		7:exit
*
*/

#ifndef pose_datan_n_codegen_protos_hh_included
#define pose_datan_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "pose_datan.hh"

// Forward Function Prototypes


#ifndef MAX_POSE_DATANAME_LENGTH
#define MAX_POSE_DATANAME_LENGTH 14
#endif
#ifndef POSE_DATANAME_LIST_LENGTH
#define POSE_DATANAME_LIST_LENGTH 2
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE pose_dataid_list[POSE_DATANAME_LIST_LENGTH];
extern const size_t pose_datasize_list[POSE_DATANAME_LIST_LENGTH];

// Enumerated Type Constants

extern int pose_dataFormat(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif pose_datan_n_codegen_protos_hh_included */ 

