/*
*	New C++ Header  File starts here.
*	This file should be named sensor_datan_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=sensor_datan.hh
*
*	.gen script :
*		0:load sensor_datan.hh
*		1:clear
*		2:select_from_file sensor_datan.hh
*		3:generate C++ protos>sensor_datan_n_codegen_protos.hh
*		4:generate C++ format>sensor_datan_n.cc
*		5:generate C++ update>sensor_datan_n.cc
*		6:generate C++ constructor>sensor_datan_n.cc
*		7:exit
*
*/

#ifndef sensor_datan_n_codegen_protos_hh_included
#define sensor_datan_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "sensor_datan.hh"
#include "offsets.hh"

// Forward Function Prototypes
extern void nmlupdate(CMS *cms, sense_data *x);
extern void initialize_sense_data(sense_data *x);


#ifndef MAX_SENSOR_DATANAME_LENGTH
#define MAX_SENSOR_DATANAME_LENGTH 16
#endif
#ifndef SENSOR_DATANAME_LIST_LENGTH
#define SENSOR_DATANAME_LIST_LENGTH 2
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE sensor_dataid_list[SENSOR_DATANAME_LIST_LENGTH];
extern const size_t sensor_datasize_list[SENSOR_DATANAME_LIST_LENGTH];

// Enumerated Type Constants

extern int sensor_dataFormat(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif sensor_datan_n_codegen_protos_hh_included */ 

