/*
*	New C++ Header  File starts here.
*	This file should be named servo_stat_cfgn_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=servo_stat_cfgn.hh
*
*	.gen script :
*		0:load servo_stat_cfgn.hh
*		1:clear
*		2:select_from_file servo_stat_cfgn.hh
*		3:generate C++ protos>servo_stat_cfgn_n_codegen_protos.hh
*		4:generate C++ format>servo_stat_cfgn_n.cc
*		5:generate C++ update>servo_stat_cfgn_n.cc
*		6:generate C++ constructor>servo_stat_cfgn_n.cc
*		7:exit
*
*/

#ifndef servo_stat_cfgn_n_codegen_protos_hh_included
#define servo_stat_cfgn_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "servo_stat_cfgn.hh"
#include "offsets.hh"

// Forward Function Prototypes


#ifndef MAX_SERVO_STAT_CFG_NAME_LENGTH
#define MAX_SERVO_STAT_CFG_NAME_LENGTH 15
#endif
#ifndef SERVO_STAT_CFG_NAME_LIST_LENGTH
#define SERVO_STAT_CFG_NAME_LIST_LENGTH 2
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE servo_stat_cfg_id_list[SERVO_STAT_CFG_NAME_LIST_LENGTH];
extern const size_t servo_stat_cfg_size_list[SERVO_STAT_CFG_NAME_LIST_LENGTH];

// Enumerated Type Constants

extern int servo_stat_cfg_format(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif servo_stat_cfgn_n_codegen_protos_hh_included */ 

