/*
*	New C++ Header  File starts here.
*	This file should be named spn_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=spn.hh
*
*	.gen script :
*		0:load spn.hh
*		1:clear
*		2:select_from_file spn.hh
*		3:generate C++ protos>spn_n_codegen_protos.hh
*		4:generate C++ format>spn_n.cc
*		5:generate C++ update>spn_n.cc
*		6:generate C++ constructor>spn_n.cc
*		7:exit
*
*/

#ifndef spn_n_codegen_protos_hh_included
#define spn_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "spn.hh"
#include "my_app_common_statusn.hh"

// Forward Function Prototypes


#ifndef MAX_SPNAME_LENGTH
#define MAX_SPNAME_LENGTH 10
#endif
#ifndef SPNAME_LIST_LENGTH
#define SPNAME_LIST_LENGTH 5
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE spid_list[SPNAME_LIST_LENGTH];
extern const size_t spsize_list[SPNAME_LIST_LENGTH];

// Enumerated Type Constants

extern int spFormat(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif spn_n_codegen_protos_hh_included */ 

