/*
*	New C++ Header  File starts here.
*	This file should be named wmn_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=wmn.hh
*
*	.gen script :
*		0:load wmn.hh
*		1:clear
*		2:select_from_file wmn.hh
*		3:generate C++ protos>wmn_n_codegen_protos.hh
*		4:generate C++ format>wmn_n.cc
*		5:generate C++ update>wmn_n.cc
*		6:generate C++ constructor>wmn_n.cc
*		7:exit
*
*/

#ifndef wmn_n_codegen_protos_hh_included
#define wmn_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "wmn.hh"
#include "my_app_common_statusn.hh"

// Forward Function Prototypes


#ifndef MAX_WMNAME_LENGTH
#define MAX_WMNAME_LENGTH 10
#endif
#ifndef WMNAME_LIST_LENGTH
#define WMNAME_LIST_LENGTH 5
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE wmid_list[WMNAME_LIST_LENGTH];
extern const size_t wmsize_list[WMNAME_LIST_LENGTH];

// Enumerated Type Constants

extern int wmFormat(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif wmn_n_codegen_protos_hh_included */ 

