

default:
	( env JSOURCE_REL_DIR="../../"  ../../build_plotter_jar.sh &&  \
	env JSOURCE_REL_DIR="../../" ../../build_jdiag_jar.sh );
	-( env JSOURCE_REL_DIR=" ../../" ../../build_plotter_NB_jar.sh );

.PHONY: default
