#!/bin/sh

if test "x${DEBUG}" = "x1" ; then
    set -x;
    echo "Running execfile_from_core.sh $* from " `pwd` >&2;
fi

gdb --batch --core $1 | grep "Core was generated by" | awk '{print $5}' | sed s#\`##g | sed s#\'##g | sed s#\\.\$## | sed s#^\\./##;
