

all:
	../etc/multiplatbuild.sh

config:
	../etc/multiplatbuild.sh config $(CONFIG_ARGS)

clean distclean check distcheck install:
	../etc/multiplatbuild.sh $@

.PHONY: all config clean distclean check distcheck install
