/*
*	New Java File starts here.
*	This file should be named EXAMPLE_MSG.java
*	Automatically generated by NML CodeGen Java Applet.
*	from /home/shackle/nml_ex1.hh:0
*	with command line arguments :  generate_for_java=true generate_for_cpp=false HHFile=/home/shackle/nml_ex1.hh
*	RCS_VERSION=2009.12.17_1575*
*	.gen script :
*		0:load /home/shackle/nml_ex1.hh
*		1:clear
*		2:select_from_file /home/shackle/nml_ex1.hh
*		3:generate Java dict>/home/shackle/nml_ex1_MsgDict.java
*		4:generate Java classes >*
*		5:exit
*
*/

// Import all NML and posemath interfaces
import rcs.nml.*;
import rcs.posemath.*;

/*
*	Class definition for EXAMPLE_MSG
*	Automatically generated by NML CodeGen Java Applet.
*/
public class EXAMPLE_MSG extends NMLmsg implements Cloneable
{
	public double d = 0;
	public float f = 0;
	public byte c = 0;
	public short s = 0;
	public int i = 0;
	public long l = 0;
	public byte uc = 0;
	public short us = 0;
	public int ui = 0;
	public long ul = 0;
	public int da_length = 0;
	public double da[] = new double[20]; /* NML_DYNAMIC_LENGTH_ARRAY */


	// Constructor 
	public EXAMPLE_MSG()
	{
		super(101);
		for(int i_da = 0; i_da < 20; i_da++ )
		{
			da[i_da]  = 0;
		}

	}



	// Constructor that should be used by any classes that extend this class. 
	protected EXAMPLE_MSG(int _type)
	{
		super(_type);
		for(int i_da = 0; i_da < 20; i_da++ )
		{
			da[i_da]  = 0;
		}

	}


	public void update(NMLFormatConverter nml_fc)
	{

		nml_fc.beginClass("EXAMPLE_MSG","NMLmsg");

		nml_fc.beginBaseClass("NMLmsg");

		super.update(nml_fc);

		nml_fc.endBaseClass("NMLmsg");
		d = nml_fc.update_with_name("d",d);
		f = nml_fc.update_with_name("f",f);
		c = nml_fc.update_with_name("c",c);
		s = nml_fc.update_with_name("s",s);
		i = nml_fc.update_with_name("i",i);
		l = nml_fc.update_with_name("l",l);
		uc = nml_fc.update_unsigned_with_name("uc",uc);
		us = nml_fc.update_unsigned_with_name("us",us);
		ui = nml_fc.update_unsigned_with_name("ui",ui);
		ul = nml_fc.update_unsigned_with_name("ul",ul);
		da_length = nml_fc.update_dla_length_with_name("da_length",da_length);
		nml_fc.update_with_name("da",da,da_length);

		nml_fc.endClass("EXAMPLE_MSG","NMLmsg");

	}


	public Object clone() throws CloneNotSupportedException
	{
		EXAMPLE_MSG cloned_object = (EXAMPLE_MSG) super.clone();
		if(this.da != null) {
			cloned_object.da = (double []) this.da.clone();
		}
		return cloned_object;

	}
}

