/*
*	New C++ Header  File starts here.
*	This file should be named exCmd_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=exCmd.hh
*	RCS_VERSION=@(#) RCS_LIBRARY_VERSION: 2009.01.26_1339 Compiled on Fri Feb  6 08:31:09 EST 2009 for the java platform.
*	$Id: CodeGenCommon.java 1341 2009-02-05 21:22:54Z shackle $
*
*	.gen script :
*		0:load exCmd.hh
*		1:clear
*		2:select_from_file exCmd.hh
*		3:generate C++ protos>exCmd_n_codegen_protos.hh
*
*/

#ifndef exCmd_n_codegen_protos_hh_included
#define exCmd_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "exCmd.hh"

// Forward Function Prototypes


#ifndef MAX_EXCMD_NAME_LENGTH
#define MAX_EXCMD_NAME_LENGTH 14
#endif
#ifndef EXCMD_NAME_LIST_LENGTH
#define EXCMD_NAME_LIST_LENGTH 5
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE exCmd_id_list[EXCMD_NAME_LIST_LENGTH];
extern const size_t exCmd_size_list[EXCMD_NAME_LIST_LENGTH];

// Enumerated Type Constants

extern int exCmd_format(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif exCmd_n_codegen_protos_hh_included */ 

