/*
*	New C++ File starts here.
*	This file should be named exStat.cc
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=exStat.hh
*	RCS_VERSION=@(#) RCS_LIBRARY_VERSION: 2009.01.26_1339 Compiled on Fri Feb  6 08:31:09 EST 2009 for the java platform.
*	$Id: CodeGenCommon.java 1341 2009-02-05 21:22:54Z shackle $
*
*	.gen script :
*		0:load exStat.hh
*		1:clear
*		2:select_from_file exStat.hh
*		3:generate C++ protos>exStat_n_codegen_protos.hh
*		4:generate C++ format>exStat_n.cc
*
*/

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "exStat.hh"

// Include externally supplied prototypes
#include "exStat_n_codegen_protos.hh"



#ifndef EXSTAT_NAME_LIST_LENGTH
#define EXSTAT_NAME_LIST_LENGTH 2
#endif

const NMLTYPE exStat_id_list[EXSTAT_NAME_LIST_LENGTH]= {
	EX_STATUS_TYPE, /* 0,6000 */
	-1};
const size_t exStat_size_list[EXSTAT_NAME_LIST_LENGTH]= {
	sizeof(EX_STATUS),
	0};


// Enumerated Type Constants

/*
Estimated_size	EX_STATUS	152
Estimated_size	MAXIMUM	152
*/
/*
*	NML/CMS Format function : exStat_format
*/
int exStat_format(NMLTYPE type, void *buffer, CMS *cms)
{

	type = cms->check_type_info(type,buffer,"exStat",
		(cms_symbol_lookup_function_t) 0,
		(const char **) 0,
		exStat_id_list,exStat_size_list,
		EXSTAT_NAME_LIST_LENGTH,
		0);

	switch(type)
	{
	case EX_STATUS_TYPE:
		((EX_STATUS *) buffer)->update(cms);
		break;

	default:
		return(0);
	}
	return 1;
}

/*
*	NML/CMS Update function for EX_STATUS
*	from exStat.hh:0
*/
void EX_STATUS::update(CMS *cms)
{

	cms->beginClass("EX_STATUS","RCS_STAT_MSG");

	RCS_STAT_MSG::update_stat_msg_base(cms);
	cms->update_with_name("position",position);

	cms->endClass("EX_STATUS","RCS_STAT_MSG");

}

/*
*	Constructor for EX_STATUS
*	from exStat.hh:0
*/
EX_STATUS::EX_STATUS()
	: RCS_STAT_MSG(EX_STATUS_TYPE,sizeof(EX_STATUS))
{

}

