/*
*	New C++ Header  File starts here.
*	This file should be named nml_ex1_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=nml_ex1.hh -o /tmp/nml_ex1.cc
*	RCS_VERSION=@(#) RCS_LIBRARY_VERSION: 2009.06.05_1506:1507 Compiled on Mon Jun  8 09:24:56 EDT 2009 for the java platform.
*	$Id: CodeGenCommon.java 1512 2009-06-10 13:23:49Z shackle $
*
*	.gen script :
*		0:load nml_ex1.hh
*		1:clear
*		2:select_from_file nml_ex1.hh
*		3:generate C++ protos>nml_ex1_n_codegen_protos.hh
*
*/

#ifndef nml_ex1_n_codegen_protos_hh_included
#define nml_ex1_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "nml_ex1.hh"

// Forward Function Prototypes


#ifndef MAX_EX_NAME_LENGTH
#define MAX_EX_NAME_LENGTH 12
#endif
#ifndef EX_NAME_LIST_LENGTH
#define EX_NAME_LIST_LENGTH 2
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE ex_id_list[EX_NAME_LIST_LENGTH];
extern const size_t ex_size_list[EX_NAME_LIST_LENGTH];

// Enumerated Type Constants

extern int ex_format(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif nml_ex1_n_codegen_protos_hh_included */ 

