/*
*	New Java File starts here.
*	This file should be named c_struct.java
*	Automatically generated by NML CodeGen Java Applet.
*	from nml_test_format.hh:77
*	with command line arguments :  generate_for_all_langs=true HHFile=nml_test_format.hh
*
*	.gen script :
*		0:load nml_test_format.hh
*		1:clear
*		2:select_from_file nml_test_format.hh
*		3:generate C protos>nml_test_format_c_n.h
*		4:generate C format>nml_test_format_c_n.c
*		5:generate C update>nml_test_format_c_n.c
*		6:generate C++ protos>nml_test_format_n_codegen_protos.hh
*		7:generate C++ format>nml_test_format_n.cc
*		8:generate C++ update>nml_test_format_n.cc
*		9:generate C++ constructor>nml_test_format_n.cc
*		10:generate Java dict>nml_test_format_MsgDict.java
*		11:generate Java classes >*
*		12:generate Ada spec>nml_test_format_n_ada.ads
*		13:generate Ada body>nml_test_format_n_ada.adb
*		14:exit
*
*/

// Import all NML and posemath interfaces
import rcs.nml.*;
import rcs.posemath.*;

/*
*	Class definition for c_struct
*	Automatically generated by NML CodeGen Java Applet.
*/
public class c_struct implements Cloneable
{
	public byte csc = 0;
	public int csi = 0;


	// Constructor 
	public c_struct()
	{

	}


	public void update(NMLFormatConverter nml_fc)
	{

		nml_fc.beginClass("c_struct",null);
		csc = nml_fc.update_with_name("csc",csc);
		csi = nml_fc.update_with_name("csi",csi);

		nml_fc.endClass("c_struct",null);

	}


	public c_struct clone() throws CloneNotSupportedException
	{
		c_struct cloned_object = (c_struct) super.clone();
		return cloned_object;

	}
}

