/*
*	New Java File starts here.
*	This file should be named teststruct_td2.java
*	Automatically generated by NML CodeGen Java Applet.
*	from nml_test_format.hh:167
*	with command line arguments :  generate_for_all_langs=true HHFile=nml_test_format.hh
*
*	.gen script :
*		0:load nml_test_format.hh
*		1:clear
*		2:select_from_file nml_test_format.hh
*		3:generate C protos>nml_test_format_c_n.h
*		4:generate C format>nml_test_format_c_n.c
*		5:generate C update>nml_test_format_c_n.c
*		6:generate C++ protos>nml_test_format_n_codegen_protos.hh
*		7:generate C++ format>nml_test_format_n.cc
*		8:generate C++ update>nml_test_format_n.cc
*		9:generate C++ constructor>nml_test_format_n.cc
*		10:generate Java dict>nml_test_format_MsgDict.java
*		11:generate Java classes >*
*		12:generate Ada spec>nml_test_format_n_ada.ads
*		13:generate Ada body>nml_test_format_n_ada.adb
*		14:exit
*
*/

// Import all NML and posemath interfaces
import rcs.nml.*;
import rcs.posemath.*;

/*
*	Class definition for teststruct_td2
*	Automatically generated by NML CodeGen Java Applet.
*/
public class teststruct_td2 implements Cloneable
{
	public c_struct2 cs2 = new c_struct2();
	public boolean b = false;
	public int i = 0;
	public byte c = 0;
	public float f = 0;
	public double d = 0;
	public boolean bool_array[] = new boolean[2];
	public int ia[] = new int[2];
	public byte ca[] = new byte[2];
	public float fa[] = new float[2];
	public double da[] = new double[2];
	public double two_d_array[] = new double[4];
	public double three_d_array[] = new double[8];
	public float f_pi = (float) 3.14159265;/* set by default comment */
	public double d_pi = (double) 3.14159265;/* set by default comment */
	public int cda_length = 0;
	public byte cda[] = new byte[2]; /* NML_DYNAMIC_LENGTH_ARRAY */
	public double seventysevenpointseven = (double) 77.7;/* set by default comment */
	public int ida_length = 0;
	public int ida[] = new int[2]; /* NML_DYNAMIC_LENGTH_ARRAY */
	public double eightyeightpointeight = (double) 88.8;/* set by default comment */
	public int fda_length = 0;
	public float fda[] = new float[2]; /* NML_DYNAMIC_LENGTH_ARRAY */
	public int dda_length = 0;
	public double dda[] = new double[2]; /* NML_DYNAMIC_LENGTH_ARRAY */
	public byte endtsbuf[] = new byte[16];


	// Constructor 
	public teststruct_td2()
	{
		for(int i_bool_array = 0; i_bool_array < 2; i_bool_array++ )
		{
			bool_array[i_bool_array]  = false;
		}
		for(int i_ia = 0; i_ia < 2; i_ia++ )
		{
			ia[i_ia]  = 0;
		}
		for(int i_ca = 0; i_ca < 2; i_ca++ )
		{
			ca[i_ca]  = 0;
		}
		for(int i_fa = 0; i_fa < 2; i_fa++ )
		{
			fa[i_fa]  = 0;
		}
		for(int i_da = 0; i_da < 2; i_da++ )
		{
			da[i_da]  = 0;
		}
		for(int i_two_d_array = 0; i_two_d_array < 4; i_two_d_array++ )
		{
			two_d_array[i_two_d_array]  = 0;
		}
		for(int i_three_d_array = 0; i_three_d_array < 8; i_three_d_array++ )
		{
			three_d_array[i_three_d_array]  = 0;
		}
		for(int i_cda = 0; i_cda < 2; i_cda++ )
		{
			cda[i_cda]  = 0;
		}
		for(int i_ida = 0; i_ida < 2; i_ida++ )
		{
			ida[i_ida]  = 0;
		}
		for(int i_fda = 0; i_fda < 2; i_fda++ )
		{
			fda[i_fda]  = 0;
		}
		for(int i_dda = 0; i_dda < 2; i_dda++ )
		{
			dda[i_dda]  = 0;
		}

			/* set by default=endts comment */
			endtsbuf[0]  =  (byte)'e';
			endtsbuf[1]  =  (byte)'n';
			endtsbuf[2]  =  (byte)'d';
			endtsbuf[3]  =  (byte)'t';
			endtsbuf[4]  =  (byte)'s';
			endtsbuf[5]  =  (byte) 0;


	}


	public void update(NMLFormatConverter nml_fc)
	{

		nml_fc.beginClass("teststruct_td2",null);
		nml_fc.beginClassVar("cs2");
		cs2.update(nml_fc);
		nml_fc.endClassVar("cs2");
		b = nml_fc.update_with_name("b",b);
		i = nml_fc.update_with_name("i",i);
		c = nml_fc.update_with_name("c",c);
		f = nml_fc.update_with_name("f",f);
		d = nml_fc.update_with_name("d",d);
		nml_fc.update_with_name("bool_array",bool_array,2);
		nml_fc.update_with_name("ia",ia,2);
		nml_fc.update_with_name("ca",ca,2);
		nml_fc.update_with_name("fa",fa,2);
		nml_fc.update_with_name("da",da,2);
		nml_fc.update_with_name("two_d_array",two_d_array,4);
		nml_fc.update_with_name("three_d_array",three_d_array,8);
		nml_fc.next_update_default("3.14159265");
		f_pi = nml_fc.update_with_name("f_pi",f_pi);
		nml_fc.next_update_default("3.14159265");
		d_pi = nml_fc.update_with_name("d_pi",d_pi);
		cda_length = nml_fc.update_dla_length_with_name("cda_length",cda_length);
		nml_fc.update_with_name("cda",cda,cda_length);
		nml_fc.next_update_default("77.7");
		seventysevenpointseven = nml_fc.update_with_name("seventysevenpointseven",seventysevenpointseven);
		ida_length = nml_fc.update_dla_length_with_name("ida_length",ida_length);
		nml_fc.update_with_name("ida",ida,ida_length);
		nml_fc.next_update_default("88.8");
		eightyeightpointeight = nml_fc.update_with_name("eightyeightpointeight",eightyeightpointeight);
		fda_length = nml_fc.update_dla_length_with_name("fda_length",fda_length);
		nml_fc.update_with_name("fda",fda,fda_length);
		dda_length = nml_fc.update_dla_length_with_name("dda_length",dda_length);
		nml_fc.update_with_name("dda",dda,dda_length);
		nml_fc.next_update_default("endts");
		nml_fc.update_with_name("endtsbuf",endtsbuf,16);

		nml_fc.endClass("teststruct_td2",null);

	}


	public teststruct_td2 clone() throws CloneNotSupportedException
	{
		teststruct_td2 cloned_object = (teststruct_td2) super.clone();
		if(this.cs2 != null) {
			cloned_object.cs2 = (c_struct2 ) this.cs2.clone();
		}
		if(this.bool_array != null) {
			cloned_object.bool_array = (boolean []) this.bool_array.clone();
		}
		if(this.ia != null) {
			cloned_object.ia = (int []) this.ia.clone();
		}
		if(this.ca != null) {
			cloned_object.ca = (byte []) this.ca.clone();
		}
		if(this.fa != null) {
			cloned_object.fa = (float []) this.fa.clone();
		}
		if(this.da != null) {
			cloned_object.da = (double []) this.da.clone();
		}
		if(this.two_d_array != null) {
			cloned_object.two_d_array = (double []) this.two_d_array.clone();
		}
		if(this.three_d_array != null) {
			cloned_object.three_d_array = (double []) this.three_d_array.clone();
		}
		if(this.cda != null) {
			cloned_object.cda = (byte []) this.cda.clone();
		}
		if(this.ida != null) {
			cloned_object.ida = (int []) this.ida.clone();
		}
		if(this.fda != null) {
			cloned_object.fda = (float []) this.fda.clone();
		}
		if(this.dda != null) {
			cloned_object.dda = (double []) this.dda.clone();
		}
		if(this.endtsbuf != null) {
			cloned_object.endtsbuf = (byte []) this.endtsbuf.clone();
		}
		return cloned_object;

	}
}

