/*
*	New C++ File starts here.
*	This file should be named nml_ex1.cc
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  generate_for_all_langs=true HHFile=nml_ex1.hh
*
*	.gen script :
*		0:load nml_ex1.hh
*		1:clear
*		2:select_from_file nml_ex1.hh
*		3:generate C protos>nml_ex1_c_n.h
*		4:generate C format>nml_ex1_c_n.c
*		5:generate C update>nml_ex1_c_n.c
*		6:generate C++ protos>nml_ex1_n_codegen_protos.hh
*		7:generate C++ format>nml_ex1_n.cc
*		8:generate C++ update>nml_ex1_n.cc
*		9:generate C++ constructor>nml_ex1_n.cc
*		10:generate Java dict>nml_ex1_MsgDict.java
*		11:generate Java classes >*
*		12:generate Ada spec>nml_ex1_n_ada.ads
*		13:generate Ada body>nml_ex1_n_ada.adb
*		14:exit
*
*/

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "nml_ex1.hh"

// Include externally supplied prototypes
#include "nml_ex1_n_codegen_protos.hh"



#ifndef EX_NAME_LIST_LENGTH
#define EX_NAME_LIST_LENGTH 2
#endif

const NMLTYPE ex_id_list[EX_NAME_LIST_LENGTH]= {
	EXAMPLE_MSG_TYPE, /* 0,101 */
	-1};
const size_t ex_size_list[EX_NAME_LIST_LENGTH]= {
	sizeof(EXAMPLE_MSG),
	0};


// Enumerated Type Constants

/*
Estimated_size	EXAMPLE_MSG	248
Estimated_size	MAXIMUM	248
*/
/*
*	NML/CMS Format function : ex_format
*/
int ex_format(NMLTYPE type, void *buffer, CMS *cms)
{

	type = cms->check_type_info(type,buffer,"ex",
		(cms_symbol_lookup_function_t) 0,
		(const char **) 0,
		ex_id_list,ex_size_list,
		EX_NAME_LIST_LENGTH,
		0);

	switch(type)
	{
	case EXAMPLE_MSG_TYPE:
		((EXAMPLE_MSG *) buffer)->update(cms);
		break;

	default:
		return(0);
	}
	return 1;
}

/*
*	NML/CMS Update function for EXAMPLE_MSG
*	from nml_ex1.hh:0
*/
void EXAMPLE_MSG::update(CMS *cms)
{

	cms->beginClass("EXAMPLE_MSG","NMLmsg");
	cms->update_with_name("d",d);
	cms->update_with_name("f",f);
	cms->update_with_name("c",c);
	cms->update_with_name("s",s);
	cms->update_with_name("i",i);
	cms->update_with_name("l",l);
	cms->update_with_name("uc",uc);
	cms->update_with_name("us",us);
	cms->update_with_name("ui",ui);
	cms->update_with_name("ul",ul);
	cms->update_dla_length_with_name("da_length",da_length);
	cms->update_dla_with_name("da",da,da_length,20);

	cms->endClass("EXAMPLE_MSG","NMLmsg");

}

