--
--	New Ada Spec File starts here.
--	This file should be named nml_ex1_n_ada.ads
--	Automatically generated by NML CodeGen Java Applet.
with Nml_Msg; use Nml_Msg;
with Cms;

with Posemath_N_Ada;  use Posemath_N_Ada;


--	Some standard Ada Packages we always need.
with Unchecked_Deallocation;
with Unchecked_Conversion;
with Interfaces.C; use Interfaces.C;

package nml_ex1_n_ada is

	-- Create Ada versions of the Enumeration types.

	function Format(Nml_Type : in long;
			Msg : in NmlMsg_Access;
			Cms_Ptr : in Cms.Cms_Access)
				return int;

	pragma Export(C,Format,"ada_nml_ex1_n_ada_format");


	-- Redefine the C++ NML message classes as Ada Records.

	EXAMPLE_MSG_TYPE : constant := 101;

	type EXAMPLE_MSG is new NMLmsg with 
		record
			d : double;
			f : c_float;
			c : char;
			s : short;
			i : int;
			l : long;
			uc : unsigned_char;
			us : unsigned_short;
			ui : unsigned;
			ul : unsigned_long;
			da_length : int;
			da : Cms.Double_Array(1..20); -- NML_DYNAMIC_LENGTH_ARRAY -- 
		end record;

	type EXAMPLE_MSG_Access is access all EXAMPLE_MSG;
	procedure Initialize(Msg : in out EXAMPLE_MSG);
	function NmlMsg_to_EXAMPLE_MSG is new Unchecked_Conversion(NmlMsg_Access,EXAMPLE_MSG_Access);
	procedure Update_Internal_EXAMPLE_MSG(Cms_Ptr : in Cms.Cms_Access; Msg : in out EXAMPLE_MSG);
	procedure Free is new Unchecked_Deallocation(EXAMPLE_MSG,EXAMPLE_MSG_Access);
	type EXAMPLE_MSG_Array is array(Integer range <>) of EXAMPLE_MSG;


end nml_ex1_n_ada;

-- End of Ada spec file  nml_ex1_n_ada.ads

