/*
*	New C++ Header  File starts here.
*	This file should be named stat_msg_v2_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=stat_msg_v2.hh
*	RCS_VERSION=@(#) RCS_LIBRARY_VERSION: 2009.06.04_1506 Compiled on Fri Jun  5 08:49:50 EDT 2009 for the java platform.
*	$Id: CodeGenCommon.java 1480 2009-05-20 15:19:27Z shackle $
*
*	.gen script :
*		0:load stat_msg_v2.hh
*		1:clear
*		2:select_from_file stat_msg_v2.hh
*		3:generate C++ protos>stat_msg_v2_n_codegen_protos.hh
*
*/

#ifndef stat_msg_v2_n_codegen_protos_hh_included
#define stat_msg_v2_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "stat_msg_v2.hh"

// Forward Function Prototypes
extern void nmlupdate(CMS *cms, struct time_tracker *x);


#ifndef MAX_RCS_STAT_MSG_V2_NAME_LENGTH
#define MAX_RCS_STAT_MSG_V2_NAME_LENGTH 1
#endif
#ifndef RCS_STAT_MSG_V2_NAME_LIST_LENGTH
#define RCS_STAT_MSG_V2_NAME_LIST_LENGTH 1
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE RCS_STAT_MSG_V2_id_list[RCS_STAT_MSG_V2_NAME_LIST_LENGTH];
extern const size_t RCS_STAT_MSG_V2_size_list[RCS_STAT_MSG_V2_NAME_LIST_LENGTH];
extern const char RCS_STAT_MSG_V2_name_list[RCS_STAT_MSG_V2_NAME_LIST_LENGTH][MAX_RCS_STAT_MSG_V2_NAME_LENGTH];
extern const char *RCS_STAT_MSG_V2_symbol_lookup(long type);


// Enumerated Type Constants

// RCS_ADMIN_STATE
#ifndef MAX_ENUM_RCS_ADMIN_STATE_STRING_LENGTH
#define MAX_ENUM_RCS_ADMIN_STATE_STRING_LENGTH 20
#endif
	/* MAX_ENUM_RCS_ADMIN_STATE_STRING_LENGTH */
#ifndef ENUM_RCS_ADMIN_STATE_LENGTH
#define ENUM_RCS_ADMIN_STATE_LENGTH 5
#endif
	/* ENUM_RCS_ADMIN_STATE_LENGTH */

extern const char *RCS_STAT_MSG_V2_enum_RCS_ADMIN_STATE_symbol_lookup(long v);

// RCS_STATUS
#ifndef MAX_ENUM_RCS_STATUS_STRING_LENGTH
#define MAX_ENUM_RCS_STATUS_STRING_LENGTH 21
#endif
	/* MAX_ENUM_RCS_STATUS_STRING_LENGTH */
#ifndef ENUM_RCS_STATUS_LENGTH
#define ENUM_RCS_STATUS_LENGTH 5
#endif
	/* ENUM_RCS_STATUS_LENGTH */

extern const char *RCS_STAT_MSG_V2_enum_RCS_STATUS_symbol_lookup(long v);

extern int RCS_STAT_MSG_V2_format(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif stat_msg_v2_n_codegen_protos_hh_included */ 

