/*
*	New C++ File starts here.
*	This file should be named timetracker_c_n.c
*/

/* Include all C language NML and CMS function prototypes. */
#include "nmlcms_c.h"

/* Include externally supplied prototypes. */
#include "timetracker_c_n.h"

/* Forward Function Prototypes */
#ifdef __cplusplus
extern "C" {
#endif

void cms_time_tracker_update(struct cms_c_struct *cms, nml_time_tracker_c_t *x);

#ifdef __cplusplus
}
#endif


/*
*	NML/CMS Update function for time_tracker
*	Automatically generated by NML CodeGen Java Applet.
*	on Mon Mar 20 05:57:09 EST 2006
*/
void cms_time_tracker_update(struct cms_c_struct *cms, nml_time_tracker_c_t *x)
{

	cms_begin_class(cms,"time_tracker",0);
	cms_update_int(cms,"count",&(x->count));
	cms_update_double(cms,"last",&(x->last));
	cms_update_double(cms,"now",&(x->now));
	cms_update_double(cms,"start",&(x->start));
	cms_update_double(cms,"elapsed",&(x->elapsed));
	cms_update_double(cms,"min",&(x->min));
	cms_update_double(cms,"max",&(x->max));
	cms_update_double(cms,"avg",&(x->avg));

	cms_end_class(cms,"time_tracker",0);

}

