/*
*	New C++ File starts here.
*	This file should be named timetracker.cc
*/

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "timetracker.hh"

// Forward Function Prototypes
void nmlupdate(CMS *cms, time_tracker *x);
void initialize_time_tracker(time_tracker *x);


/*
*	NML/CMS Update function for time_tracker
*	Automatically generated by NML CodeGen Java Applet.
*	on Mon Mar 20 05:57:09 EST 2006
*/
void nmlupdate(CMS *cms,time_tracker *x)
{

	cms->beginClass("time_tracker",0);
	cms->update_with_name("count",x->count);
	cms->update_with_name("last",x->last);
	cms->update_with_name("now",x->now);
	cms->update_with_name("start",x->start);
	cms->update_with_name("elapsed",x->elapsed);
	cms->update_with_name("min",x->min);
	cms->update_with_name("max",x->max);
	cms->update_with_name("avg",x->avg);

	cms->endClass("time_tracker",0);

}

